# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build and Release Artifacts
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            8, # Default build
            11,
            16
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: gradle
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '8' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/


  release:
    needs: build
    runs-on: ubuntu-20.04

    if: startsWith(github.ref, 'refs/heads/release')

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: Artifacts
          path: bin

      - name: Make and Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          tag_name: ${{ steps.previoustag.outputs.tag }}
          fail_on_unmatched_files: false
          body: |
            <CHANGELOG>

            Make sure to read the [README](README.md) for instructions on how this mod works and how to use it.\
